stages:
  - containerize
  - deploy

variables:
  DOCKER_BUILDKIT: 1

include:
  - project: 'cicd/gitlab-ci-templates'
    file: 'containerize/docker-ucrb-yarn.yml'
  - project: 'cicd/gitlab-ci-templates'
    file: 'deploy/deploy-universal.yml'

dockerize_test:
  image: registry-proxy.alfa-bank.kz/docker:20.10
dockerize_prod:
  image: registry-proxy.alfa-bank.kz/docker:20.10
